language: python
python:
  - "3.5"
install:
  - "pip install pytest pytest-cov coveralls && pip install -r server/requirements.txt"
script: py.test --cov=newmansound
after_success:
  - coveralls
