language: python
python:
  - "3.5"
install:
  - "pip install pytest pytest-cov flask flask_restful marshmallow sqlalchemy coveralls"
script: py.test --cov=newmansound
after_success:
  - coveralls
